/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Hanging_Pot: THREE.Mesh;
  };
  materials: {
    palette: THREE.MeshStandardMaterial;
  };
};

export function HangingPotModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/VoxelHangingPot-transformed.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Hanging_Pot.geometry}
        material={materials.palette}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/VoxelHangingPot-transformed.glb");
