/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/VoxelRoomBlend.glb --typescript --transform -o src/components/experience/gltfjsx/RoomModel.tsx 
Files: public/models/VoxelRoomBlend.glb [5.52MB] > C:\Users\janto\OneDrive\Documentos\PC\PROYECTOS\REPOS\cozy-room-portfolio\src\components\experience\gltfjsx\VoxelRoomBlend-transformed.glb [175.16KB] (97%)
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    VoxelRoom: THREE.Mesh;
  };
  materials: {
    ["palette.013"]: THREE.MeshPhysicalMaterial;
  };
};

export function RoomModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/VoxelRoomBlend-transformed.glb",
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.VoxelRoom.geometry}
        position={[0.21, 0.29, 0.18]}
        rotation={[0, Math.PI / 2, 0]}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial map={materials["palette.013"].map} roughness={0.9} metalness={0} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/VoxelRoomBlend-transformed.glb");
