/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/VoxelSWDock.glb --typescript --transform -o src/components/experience/gltfjsx/SWDockModel.tsx 
Files: public/models/VoxelSWDock.glb [9.18KB] > C:\Users\janto\OneDrive\Documentos\PC\PROYECTOS\REPOS\cozy-room-portfolio\src\components\experience\gltfjsx\VoxelSWDock-transformed.glb [2.59KB] (72%)
*/

import * as THREE from "three";
import { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    SW_Dock: THREE.Mesh;
  };
  materials: {
    palette: THREE.MeshStandardMaterial;
  };
};

export function SWDockModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/VoxelSWDock-transformed.glb",
  ) as unknown as GLTFResult;

  return (
    <group
      {...props}
      dispose={null}
      position={[-0.85, -0.39, -0.39]}
      scale={1.3}
      rotation={[0, 1.3, 0]}
      castShadow
      receiveShadow
      raycast={() => null}
    >
      <mesh raycast={() => null} geometry={nodes.SW_Dock.geometry} material={materials.palette} />
    </group>
  );
}

useGLTF.preload("/models/VoxelSWDock-transformed.glb");
