/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { JSX, useEffect, useRef, useState } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    GB_Cartridge: THREE.Mesh;
    GB_Console: THREE.Mesh;
  };
  materials: {
    palette: THREE.MeshPhysicalMaterial;
    ["palette.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function VoxelGBModel(props: JSX.IntrinsicElements["group"]) {
  const groupRef = useRef<THREE.Group>(null!);
  const cartridgeRef = useRef<THREE.Mesh>(null!);
  const { nodes, materials } = useGLTF("/models/VoxelGB.glb") as unknown as GLTFResult;
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    if (hovered) {
      gsap.to(groupRef.current.scale, {
        x: 1.2,
        y: 1.2,
        z: 1.2,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(groupRef.current.position, {
        y: -0.36,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(cartridgeRef.current.position, {
        y: 0.1,
        duration: 0.2,
        ease: "power2.out",
      });
    } else {
      gsap.to(groupRef.current.scale, {
        x: 1.1,
        y: 1.1,
        z: 1.1,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(groupRef.current.position, {
        y: -0.38,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(cartridgeRef.current.position, {
        y: 0.0488,
        duration: 0.2,
        ease: "power2.out",
      });
    }
  }, [hovered]);

  return (
    <group
      ref={groupRef}
      {...props}
      dispose={null}
      position={[-0.66, -0.38, 0.735]}
      rotation={[Math.PI * 0.5, 2.1, Math.PI * -0.5]}
      scale={1.1}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <mesh
        ref={cartridgeRef}
        castShadow
        receiveShadow
        geometry={nodes.GB_Cartridge.geometry}
        material={materials.palette}
        position={[0.0004, 0.0488, -0.0124]}
      >
        <Outlines visible={hovered} thickness={3} color="white" />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GB_Console.geometry}
        material={materials.palette}
      >
        <Outlines visible={hovered} thickness={3} color="white" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/VoxelGB.glb");
