/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { JSX, useEffect, useRef, useState } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    ["3ds_Base"]: THREE.Mesh;
    ["3ds_Screen"]: THREE.Mesh;
  };
  materials: {
    palette: THREE.MeshPhysicalMaterial;
  };
};

export function Voxel3dsModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/Voxel3ds.glb") as unknown as GLTFResult;
  const baseRef = useRef<THREE.Mesh>(null!);
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    if (hovered) {
      gsap.to(baseRef.current.scale, {
        x: 1.1,
        y: 1.1,
        z: 1.1,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(baseRef.current.position, {
        y: 0.01,
        duration: 0.2,
        ease: "power2.out",
      });
    } else {
      gsap.to(baseRef.current.scale, {
        x: 1,
        y: 1,
        z: 1,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(baseRef.current.position, {
        y: 0,
        duration: 0.2,
        ease: "power2.out",
      });
    }
  }, [hovered]);

  return (
    <group
      {...props}
      dispose={null}
      position={[-0.6, -0.467, 0.5]}
      rotation={[0, Math.PI * 0.5, 0]}
      scale={1.2}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <mesh
        ref={baseRef}
        castShadow
        receiveShadow
        geometry={nodes["3ds_Base"].geometry}
        material={materials.palette}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3ds_Screen"].geometry}
          material={materials.palette}
          position={[0.001, 0.0072, -0.0455]}
        >
          <Outlines visible={hovered} thickness={3} color="white" />
        </mesh>
        <Outlines visible={hovered} thickness={3} color="white" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Voxel3ds.glb");
