/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/VoxelChu.glb --typescript --transform -o src/components/experience/gltfjsx/VoxelChuModel.tsx 
Files: public/models/VoxelChu.glb [46.88KB] > C:\Users\janto\OneDrive\Documentos\PC\PROYECTOS\REPOS\cozy-room-portfolio\src\components\experience\gltfjsx\VoxelChu-transformed.glb [5.32KB] (89%)
*/

import * as THREE from "three";
import { JSX, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import gsap from "gsap";
import { Howl } from "howler";
import { useStore } from "@/store";

type GLTFResult = GLTF & {
  nodes: {
    Pika_R_Arm: THREE.Mesh;
    Pika_Body: THREE.Mesh;
  };
  materials: {
    palette: THREE.MeshStandardMaterial;
    ["palette.002"]: THREE.MeshStandardMaterial;
  };
};

export function VoxelChuModel(props: JSX.IntrinsicElements["group"]) {
  const isSoundEnabled = useStore((state) => state.isSoundEnabled);
  const modelRef = useRef<THREE.Group>(null!);
  const [isHappy, setIsHappy] = useState(false);

  const soundRef = useRef(
    new Howl({
      src: ["/sounds/shine.mp3"],
      volume: 0.3,
      rate: 1.1,
    }),
  );

  const hasPlayedSound = useRef(false);

  const { nodes, materials } = useGLTF("/models/VoxelChu-transformed.glb") as unknown as GLTFResult;

  const handlePointerDown = () => {
    if (isHappy) return;
    setIsHappy(true);

    if (!hasPlayedSound.current && isSoundEnabled) {
      hasPlayedSound.current = true;
      soundRef.current.play();
    }

    gsap.to(modelRef.current.scale, {
      x: "+=0.3",
      y: "+=0.3",
      z: "+=0.3",
      duration: 0.5,
      yoyo: true,
      repeat: 1,
      ease: "elastic.inOut",
      onComplete: () => setIsHappy(false),
    });

    gsap.to(modelRef.current.position, {
      y: "+=0.08",
      duration: 0.5,
      yoyo: true,
      repeat: 1,
      ease: "elastic.inOut",
      onComplete: () => setIsHappy(false),
    });
  };

  return (
    <group
      ref={modelRef}
      {...props}
      dispose={null}
      onPointerDown={handlePointerDown}
      position={[-0.5, 0.39, -1.15]}
    >
      <mesh
        geometry={nodes.Pika_R_Arm.geometry}
        material={materials.palette}
        position={[-0.019, -0.017, 0.018]}
        rotation={[2.618, 0.688, -2.372]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Pika_Body.geometry}
        material={materials["palette.002"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/models/VoxelChu-transformed.glb");
