/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { JSX, useEffect, useRef, useState } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import gsap from "gsap";
import { useStore } from "@/store";
import ConsoleGBContent from "../console-ui/gb/ConsoleGBContent";
import TitleLabelThree from "../console-ui/components/TitelLabelThree";

type GLTFResult = GLTF & {
  nodes: {
    GB_Cartridge: THREE.Mesh;
    GB_Console: THREE.Mesh;
  };
  materials: {
    palette: THREE.MeshPhysicalMaterial;
    ["palette.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function VoxelGBModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/VoxelGB.glb") as unknown as GLTFResult;

  const setFocus = useStore((state) => state.setFocus);
  const focus = useStore((state) => state.focus);

  const groupRef = useRef<THREE.Group>(null!);
  const cartridgeRef = useRef<THREE.Mesh>(null!);
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    if (focus === "gb") {
      gsap.to(groupRef.current.position, {
        x: 1.41,
        y: 0.147,
        z: 1.41,
        duration: 0.7,
        ease: "power2.out",
      });
      gsap.to(groupRef.current.rotation, {
        x: 1.96 * Math.PI,
        y: 0.25 * Math.PI,
        z: 0.0275 * Math.PI,
        duration: 0.6,
        ease: "power2.out",
      });
    } else if (hovered && focus === "idle") {
      gsap.to(groupRef.current.scale, {
        x: 1.2,
        y: 1.2,
        z: 1.2,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(groupRef.current.position, {
        y: -0.36,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(cartridgeRef.current.position, {
        y: 0.1,
        duration: 0.2,
        ease: "power2.out",
      });
    } else {
      gsap.to(groupRef.current.scale, {
        x: 1.1,
        y: 1.1,
        z: 1.1,
        duration: 0.2,
        ease: "power2.out",
      });
      gsap.to(groupRef.current.position, {
        x: -0.66,
        y: -0.38,
        z: 0.735,
        duration: 0.6,
        ease: "power2.out",
      });
      gsap.to(groupRef.current.rotation, {
        x: Math.PI * 0.5,
        y: 2.1,
        z: Math.PI * -0.5,
        duration: 0.5,
        ease: "power2.out",
      });
      gsap.to(cartridgeRef.current.position, {
        y: 0.0488,
        duration: 0.2,
        ease: "power2.out",
      });
    }
  }, [focus, hovered]);

  return (
    <group
      {...props}
      ref={groupRef}
      dispose={null}
      position={[-0.66, -0.38, 0.735]}
      rotation={[Math.PI * 0.5, 2.1, Math.PI * -0.5]}
      scale={1.1}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
      onClick={(e) => {
        e.stopPropagation();
        if (focus === "idle") {
          setFocus("gb");
        }
      }}
    >
      <mesh
        ref={cartridgeRef}
        castShadow
        receiveShadow
        geometry={nodes.GB_Cartridge.geometry}
        material={materials.palette}
        position={[0.0004, 0.0488, -0.0124]}
      >
        <Outlines visible={hovered && focus === "idle"} thickness={3} color="white" />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GB_Console.geometry}
        material={materials.palette}
      >
        {focus === "gb" && <ConsoleGBContent />}
        <Outlines visible={hovered && focus === "idle"} thickness={3} color="white" />
      </mesh>
      {hovered && focus === "idle" && <TitleLabelThree title="About" position={[-0.05, 0.25, 0]} />}
    </group>
  );
}

useGLTF.preload("/models/VoxelGB.glb");
